version: "3"

services:
  app:
    container_name: "UDAppDev"
    image: dcloud.hicrystal.com/ultimate_division:latest
    ports:
      - "8087:8087" # Forward the exposed port 5000 on the container to port 8088 on the host machine (8088:5000).
      - "8088:8088"
    restart: unless-stopped
    volumes:
      - ${PROJECT_DIRECTORY}/data/ultimate_division:/app/data
      - ${PROJECT_DIRECTORY}/configs/ultimate_division:/config
      - ${PROJECT_DIRECTORY}/assets:/assets
    depends_on:
      - ultimatedivisiondb_dev # This service depends on postgres. Start that first.
    networks:
      - fullstack

  nft_signer:
    container_name: "UDNFTSignerDev"
    image: dcloud.hicrystal.com/ultimate_division_nft_signer:latest
    restart: unless-stopped
    volumes:
      - ${PROJECT_DIRECTORY}/data/signer:/app/data
      - ${PROJECT_DIRECTORY}/configs/nft_signer:/config
    depends_on:
      - ultimatedivisiondb_dev # This service depends on postgres. Start that first.
    networks:
      - fullstack

  currency_signer:
    container_name: "UDCurrencySignerDev"
    image: dcloud.hicrystal.com/ultimate_division_currency_signer:latest
    restart: unless-stopped
    volumes:
      - ${PROJECT_DIRECTORY}/data/currency_signer:/app/data
      - ${PROJECT_DIRECTORY}/configs/currency_signer:/config
    depends_on:
      - ultimatedivisiondb_dev # This service depends on postgres. Start that first.
    networks:
      - fullstack

  ultimatedivisiondb_dev:
    restart: always
    image: postgres:latest
    container_name: ultimatedivisiondb_dev
    ports:
      - "5635:5432"
    volumes:
      - ${PROJECT_DIRECTORY}/data/db:/var/lib/postgresql/data
    networks:
      - fullstack
    environment:
      - POSTGRES_DB=ultimatedivisiondb_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge