# This is a basic workflow to help you get started with Actions

name: CI prod
env:
  DOCKER_VERSION : ${{ github.sha }}

## Controls when the workflow will run
#on:
#  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ master ]

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Main master"]
    types:
      - completed
    push:
      branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.7

      # Runs a single command using the runners shell
      - name: Build & push docker images to our server
        run:  make docker_prod VERSION=${{ env.DOCKER_VERSION }}

      # Configure Server credential
      - name: Configure my Server credential
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -p 55228 -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy PROD environment images
        run: deploy /home/valerii/storage/docker/ultimatedivisionAppProd/docker-compose.yml