name: Main master
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: ultimatedivisiondb_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Set up Go 1.15.6
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.6
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Build
        run: go install ./... .
      - name: Lint
        uses: BoostyLabs/golangci-lint@master
        with:
          args: "run"
        env:
          GOROOT: ""
      - name: Test
        run: go test ./... .
